global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'sleuth-open-telemetry'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:9001' ]
        labels:
          application: 'sleuth-open-telemetry'
